{{- if .Values.agentActions.enabled }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: castai-agent-actions
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
  {{- with .Values.agentActions.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: castai-agent-actions
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
rules:
  # Readonly.
  - apiGroups: [ "" ]
    resources: [ "pods", "nodes" ]
    verbs: [ "get", "list" ]
  # For node draining and patching.
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "patch", "update" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods/eviction" ]
    verbs: [ "create" ]
  # For node deletion.
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "delete" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: castai-agent-actions
  labels:
    {{- include "castai-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: castai-agent-actions
subjects:
  - kind: ServiceAccount
    name: castai-agent-actions
    namespace: {{ .Values.namespace }}


{{- end }}