ingress-nginx:
  controller:
    replicaCount: 1
    service:
      type: LoadBalancer
      annotations:
        service.kubernetes.io/loadbalancer-healthcheck-protocol: "https"
        service.kubernetes.io/loadbalancer-healthcheck-port: "443"
        service.kubernetes.io/loadbalancer-healthcheck-path: "/healthz"
    admissionWebhooks:
      enabled: false
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - ingress-nginx
            topologyKey: "kubernetes.io/hostname"
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - ingress-nginx
              topologyKey: "topology.cast.ai/csp"
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"
