grafana:
  fullnameOverride: grafana
  grafana.ini:
    server:
      serve_from_sub_path: true
      root_url: /api/v1/namespaces/grafana-bundle/services/http:grafana:80/proxy/
    analytics:
      check_for_updates: false
    grafana_net:
      url: https://grafana.net
    log:
      mode: console
    paths:
      data: /var/lib/grafana/data
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Admin
    users:
      default_theme: light
  sidecar:
    imagePullPolicy: IfNotPresent
    dashboards:
      enabled: true
      label: grafana_dashboard
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
    portName: http
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.castai-prometheus:9090
          access: proxy
        - name: Loki
          type: loki
          url: http://loki:3100
          access: proxy
          isDefault: true


# Dashboards are converted to config maps and imported to Grafana using it's sidecar.
dashboards:
  etcd:
    file: dashboards/etcd.json
  ingress-nginx:
    file: dashboards/ingress-nginx.json
  kubernetes:
    file: dashboards/kubernetes.json

loki:
  fullnameOverride: loki
  enabled: true
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 10Gi
  config:
    auth_enabled: false
    ingester:
      chunk_idle_period: 3m
      chunk_block_size: 262144
      chunk_retain_period: 1m
      max_transfer_retries: 0
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    server:
      http_listen_port: 3100
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
    compactor:
      working_directory: /data/loki/boltdb-shipper-compactor
      shared_store: filesystem

promtail:
  enabled: true
  fullnameOverride: promtail
  loki:
    serviceName: "loki"
    servicePort: 3100
