apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-webhook-health"
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: webhook-health
    app.kubernetes.io/name: webhook-health
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "webhook-health"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6080
      targetPort: 6080
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "webhook"
